name: dero
description: Dero Wallet

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider_architecture: ^1.0.5
  package_info: ^0.4.0+13
  qr_flutter: ^3.2.0
  barcode_scan: ^1.0.0
  path: ^1.6.4
  path_provider: ^1.6.0
  #  file_picker: ^1.3.8
  permission_handler: ^4.2.0+hotfix.3
#  path_provider_ex: ^1.0.1
  #  folder_file_saver: ^0.4.0
  protobuf: ^1.0.1
  fixnum: ^0.10.11
  provider: ^4.0.3
  get_it: ^3.0.1
  flutter_form_builder: ^3.7.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  auto_size_text: ^2.1.0
  modal_progress_hud: ^0.1.3
  shared_preferences: ^0.5.6+1
  #  folder_picker: ^0.2.1
  #  flutter_slidable: "^0.5.3"
  url_launcher: ^5.4.1
  share: ^0.6.3+5
  #  keyboard_actions: ^2.1.2
  loading: ^1.0.2
  flushbar: ^1.9.1
  flutter_screenutil: ^1.0.2
  intl: ^0.16.1
  http: ^0.12.0+4
  json_annotation: ^3.0.1
#  folder_picker: ^0.3.0
  share_extend: ^1.1.1
  file_picker: ^1.4.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4
  intl_translation: ^0.17.9
  build_runner: ^1.7.4
  json_serializable: ^3.2.5


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/logo.png
    - assets/images/logo_no_background.png
  fonts:
    - family: AppIcons
      fonts:
        - asset: fonts/AppIcons.ttf
    - family: NunitoSans
      fonts:
        - asset: fonts/NunitoSans-Bold.ttf
        - asset: fonts/NunitoSans-ExtraBold.ttf
        - asset: fonts/NunitoSans-ExtraLight.ttf
        - asset: fonts/NunitoSans-Light.ttf
        - asset: fonts/NunitoSans-Regular.ttf
        - asset: fonts/NunitoSans-SemiBold.ttf
    - family: OverpassMono
      fonts:
        - asset: fonts/OverpassMono-Light.ttf
        - asset: fonts/OverpassMono-Regular.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/logo.png"
  image_path_ios: "assets/images/logo.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/images/logo.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/logo.png" # only available for Android 8.0 devices and above